import os
from pathlib import Path

def rewrite_file(path, lines):
    content = '\n'.join(lines) + '\n'
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(content)
    actual = len(Path(path).read_text(encoding='utf-8').splitlines())
    print(f'Rewrote {path}, lines: {actual}')
    assert actual >= 20, f'File {path} is too small!'

README_md_lines: list[str] = [
    '# Pictovap',
    '',
    'Open-source visual finishing for content publishers.',
    '',
    'Pictovap turns unfinished articles into visually complete, rights-aware, publish-ready CMS pages.',
    '',
    '## What is Pictovap?',
    '',
    "It is the missing article-aware layer between written content and CMS publishing. It reads an article's structure, creates a visual brief, evaluates candidate images, records provenance, generates metadata, and produces CMS placement instructions.",
    '',
    'Pictovap is **not** a stock photo search tool, a DAM, or a generic AI image generator.',
    '',
    '## Why it exists',
    '',
    'Independent publishers spend significant time on visual operations per article: finding images, checking licenses, resizing, writing alt text, and placing them in a CMS. This labor scales linearly with article volume. Pictovap automates this workflow so editors can focus on narrative quality.',
    '',
    '## Quickstart',
    '',
    'Get Pictovap running locally in under five minutes.',
    '',
    '```bash',
    'git clone https://github.com/yoldaolmak/Pictovap.git',
    'cd Pictovap',
    'python3 -m venv .venv',
    'source .venv/bin/activate',
    'pip install -r requirements.txt',
    'pip install -e .',
    '```',
    '',
    'Run the local credential-free demo:',
    '',
    '```bash',
    'make demo',
    '```',
    '',
    '## Demo Output',
    '',
    'The demo runs the entire pipeline locally and outputs a summary of what it did:',
    '',
    '```text',
    '  Brief:      4 slots from 3 sections',
    '  Evaluated:  5 candidates',
    '  Selected:   3 images',
    '  Rejected:   4 candidates',
    '  Placements: 3 instructions',
    '```',
    '',
    '## Four Primitives',
    '',
    'Pictovap operates on four core architectural primitives:',
    '',
    '1. **Visual Brief:** Analyzes the article to determine exactly what imagery is needed.',
    '2. **Fit Score:** Evaluates candidates deterministically against contextual, technical, and licensing criteria.',
    '3. **Provenance Pack:** Maintains an audit trail tracking image origin, license, and processing actions.',
    '4. **CMS Placement:** Produces a CMS-agnostic plan for where images should be injected.',
    '',
    '## Adapter Model',
    '',
    'Pictovap uses an adapter-based architecture:',
    '',
    '- **Image Sources:** Local folder, Unsplash, DepositPhotos, Visual Memory DB.',
    '- **CMS Placement:** WordPress (working), Ghost (stub), Strapi (stub).',
    '',
    '## Current Limitations',
    '',
    '- Core logic was recently extracted from production; some internal dict passing is still being migrated to strict primitives.',
    '- The local demo uses mock assets rather than live API calls.',
    '- Only the WordPress CMS adapter is production-hardened; others are reference implementations.',
    '',
    '## Contributing',
    '',
    'See the [Documentation Portal](docs/README.md) for full guides on architecture, concepts, and contribution.',
    '',
    '## Compatibility Note',
    '',
    'Product name: Pictovap.',
    'Python package and legacy CLI may remain `pictova` for backward compatibility.',
]
rewrite_file('README.md', README_md_lines)

Makefile_lines: list[str] = [
    '.PHONY: install test lint clean demo help venv check-docs',
    '',
    'help:',
    '\t@echo "Pictovap - Visual Finishing Engine"',
    '\t@echo ""',
    '\t@echo "Available targets:"',
    '\t@echo "  demo        Run the local credential-free demo"',
    '\t@echo "  test        Run test suite"',
    '\t@echo "  install     Install dependencies"',
    '\t@echo "  lint        Run code linters"',
    '\t@echo "  clean       Clean temporary files"',
    '\t@echo "  venv        Create virtual environment"',
    '\t@echo "  check-docs  Check documentation link integrity"',
    '',
    'demo:',
    '\tpython3 -m pictova.demo',
    '',
    'install:',
    '\tpip install -r requirements.txt',
    '\tpip install -e .',
    '',
    'test:',
    '\tpytest tests/unit -v',
    '',
    'lint:',
    '\tflake8 src/ --max-line-length=120',
    '',
    'clean:',
    '\tfind . -type d -name "__pycache__" -exec rm -rf {} +',
    '\tfind . -type f -name "*.pyc" -delete',
    '\tfind . -type d -name "*.egg-info" -exec rm -rf {} +',
    '\trm -rf .pytest_cache .coverage',
    '',
    'venv:',
    '\tpython3 -m venv .venv',
    '',
    'check-docs:',
    '\tpytest tests/unit/test_demo.py::test_docs_readme_links_resolve -v',
]
rewrite_file('Makefile', Makefile_lines)

_github_workflows_ci_yml_lines: list[str] = [
    'name: CI',
    '',
    'on:',
    '  push:',
    '    branches: [main, develop]',
    '  pull_request:',
    '    branches: [main]',
    '',
    'jobs:',
    '  test:',
    '    runs-on: ubuntu-latest',
    '    strategy:',
    '      matrix:',
    '        python-version: ["3.10", "3.11", "3.12"]',
    '',
    '    steps:',
    '      - uses: actions/checkout@v4',
    '',
    '      - name: Set up Python ${{ matrix.python-version }}',
    '        uses: actions/setup-python@v5',
    '        with:',
    '          python-version: ${{ matrix.python-version }}',
    '',
    '      - name: Cache dependencies',
    '        uses: actions/cache@v4',
    '        with:',
    '          path: ~/.cache/pip',
    "          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}",
    '          restore-keys: |',
    '            ${{ runner.os }}-pip-',
    '',
    '      - name: Install dependencies',
    '        run: |',
    '          python -m pip install --upgrade pip',
    '          pip install -r requirements.txt',
    '          pip install -e .',
    '',
    '      - name: Run unit tests',
    '        run: pytest tests/unit -v',
    '',
    '      - name: Demo smoke test',
    '        run: python -m pictova.demo',
    '',
    '  lint:',
    '    runs-on: ubuntu-latest',
    '',
    '    steps:',
    '      - uses: actions/checkout@v4',
    '',
    '      - name: Set up Python',
    '        uses: actions/setup-python@v5',
    '        with:',
    '          python-version: "3.12"',
    '',
    '      - name: Install linters',
    '        run: pip install flake8',
    '',
    '      - name: Run flake8',
    '        run: flake8 src/ --max-line-length=120',
]
rewrite_file('.github/workflows/ci.yml', _github_workflows_ci_yml_lines)

src_pictova_demo_py_lines: list[str] = [
    '#!/usr/bin/env python3',
    '"""',
    'Pictovap Local Demo',
    '-------------------',
    'Runs the full visual finishing pipeline with no external credentials.',
    '',
    'Usage:',
    '    python -m pictova.demo',
    '    python examples/demo.py',
    '    make demo',
    '"""',
    '',
    'import json',
    'import hashlib',
    'import sys',
    'from pathlib import Path',
    '',
    '# Add src to path when run directly from repo root',
    'sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))',
    '',
    'from pictova.core.primitives import (',
    '    VisualBrief,',
    '    FitScore,',
    '    ProvenancePack,',
    '    CMSPlacement,',
    '    PlacementInstruction,',
    ')',
    'from pictova.core.profile import PublisherProfile',
    '',
    '',
    '# ---------------------------------------------------------------------------',
    '# Mock image candidates (no external APIs, no credentials)',
    '# ---------------------------------------------------------------------------',
    'MOCK_CANDIDATES = [',
    '    {',
    '        "id": "img-backpack-01",',
    '        "filename": "minimal-backpack.jpg",',
    '        "provider": "local",',
    '        "source_type": "local",',
    '        "local_path": "examples/assets/minimal-backpack.jpg",',
    '        "license": "CC0",',
    '        "attribution": None,',
    '        "keywords": ["backpack", "travel", "minimalist", "packing"],',
    '        "width": 1920,',
    '        "height": 1280,',
    '    },',
    '    {',
    '        "id": "img-forest-02",',
    '        "filename": "forest-path.jpg",',
    '        "provider": "local",',
    '        "source_type": "local",',
    '        "local_path": "examples/assets/forest-path.jpg",',
    '        "license": "CC0",',
    '        "attribution": None,',
    '        "keywords": ["forest", "nature", "path", "serenity", "trees"],',
    '        "width": 1600,',
    '        "height": 1067,',
    '    },',
    '    {',
    '        "id": "img-generic-03",',
    '        "filename": "generic-stock.jpg",',
    '        "provider": "stock",',
    '        "source_type": "api",',
    '        "local_path": None,',
    '        "source_url": "https://example.com/generic-stock.jpg",',
    '        "license": "editorial",',
    '        "attribution": "Example Stock Co.",',
    '        "keywords": ["map", "tourist", "generic"],',
    '        "width": 800,',
    '        "height": 600,',
    '    },',
    '    {',
    '        "id": "img-lowres-04",',
    '        "filename": "blurry-phone.jpg",',
    '        "provider": "local",',
    '        "source_type": "local",',
    '        "local_path": "examples/assets/blurry-phone.jpg",',
    '        "license": "owned",',
    '        "attribution": None,',
    '        "keywords": ["phone", "blurry", "travel"],',
    '        "width": 320,',
    '        "height": 240,',
    '    },',
    '    {',
    '        "id": "img-sunset-05",',
    '        "filename": "sunset-mountains.jpg",',
    '        "provider": "unsplash_mock",',
    '        "source_type": "api",',
    '        "local_path": None,',
    '        "source_url": "https://unsplash.com/photos/mock-sunset",',
    '        "license": "unsplash",',
    '        "attribution": "Photo by Jane Doe on Unsplash",',
    '        "keywords": ["sunset", "mountains", "nature", "travel", "landscape"],',
    '        "width": 2400,',
    '        "height": 1600,',
    '    },',
    ']',
    '',
    '',
    '# ---------------------------------------------------------------------------',
    '# Deterministic scoring (rule-based, not ML)',
    '# ---------------------------------------------------------------------------',
    'def score_candidate(candidate: dict, slot: dict, brief: VisualBrief) -> FitScore:',
    '    """Score a candidate image against a slot using deterministic rules."""',
    '    slot_id = slot.get("slot_id", "")',
    '    slot_purpose = slot.get("purpose", "")',
    '    target_heading = slot.get("target_heading", "")',
    '',
    '    # Contextual relevance: keyword overlap with article topic + title',
    '    topic_words = set((brief.topic + " " + brief.article_title).lower().split())',
    '    kw = set(k.lower() for k in candidate.get("keywords", []))',
    '    overlap = len(topic_words & kw)',
    '    contextual = min(overlap / max(len(topic_words), 1) * 5.0, 5.0)',
    '',
    '    # Section relevance: keyword overlap with target heading',
    '    section_words = set(target_heading.lower().split()) if target_heading else set()',
    '    section_overlap = len(section_words & kw)',
    '    section_rel = min(section_overlap / max(len(section_words), 1) * 3.0, 3.0) if section_words else 1.5',
    '',
    '    # Technical quality: based on resolution',
    '    w = candidate.get("width", 0)',
    '    h = candidate.get("height", 0)',
    '    if w >= 1200 and h >= 800:',
    '        tech = 3.0',
    '    elif w >= 800 and h >= 600:',
    '        tech = 2.0',
    '    else:',
    '        tech = 0.5',
    '',
    '    # Duplication risk: simple stub (always 0 in demo)',
    '    dup_risk = 0.0',
    '',
    '    # Source trust',
    '    provider = candidate.get("provider", "")',
    '    trust_map = {"local": 2.0, "unsplash_mock": 1.5, "stock": 1.0}',
    '    source_trust = trust_map.get(provider, 1.0)',
    '',
    '    # License confidence',
    '    lic = candidate.get("license", "unknown")',
    '    lic_map = {"CC0": 2.0, "owned": 2.0, "unsplash": 1.5, "editorial": 0.5, "unknown": 0.0}',
    '    license_conf = lic_map.get(lic, 0.5)',
    '',
    '    # CMS suitability: landscape preferred for featured',
    '    if slot_purpose == "featured_image":',
    '        cms_suit = 2.0 if w > h else 1.0',
    '    else:',
    '        cms_suit = 1.5',
    '',
    '    final = contextual + section_rel + tech + source_trust + license_conf + cms_suit - dup_risk',
    '',
    '    # Decision',
    '    if tech < 1.0:',
    '        decision = "rejected"',
    '        reason = f"Resolution too low ({w}x{h})"',
    '    elif license_conf < 0.5:',
    '        decision = "rejected"',
    '        reason = f"License status unclear ({lic})"',
    '    elif final >= 8.0:',
    '        decision = "selected"',
    '        reason = f"Strong fit: contextual={contextual:.1f}, quality={tech:.1f}, license={license_conf:.1f}"',
    '    else:',
    '        decision = "needs_review"',
    '        reason = f"Moderate fit (score={final:.1f}), manual review recommended"',
    '',
    '    return FitScore(',
    '        candidate_id=candidate["id"],',
    '        slot_id=slot_id,',
    '        contextual_relevance=round(contextual, 2),',
    '        section_relevance=round(section_rel, 2),',
    '        technical_quality=tech,',
    '        duplication_risk=dup_risk,',
    '        source_trust=source_trust,',
    '        license_confidence=license_conf,',
    '        cms_suitability=cms_suit,',
    '        final_score=round(final, 2),',
    '        decision=decision,',
    '        human_reason=reason,',
    '    )',
    '',
    '',
    '# ---------------------------------------------------------------------------',
    '# Demo runner',
    '# ---------------------------------------------------------------------------',
    'def run_demo():',
    '    """Run the full Pictovap demo pipeline."""',
    '    print("=" * 60)',
    '    print("  Pictovap Local Demo")',
    '    print("  Visual finishing pipeline — no credentials required")',
    '    print("=" * 60)',
    '',
    '    # 1. Load publisher profile',
    '    profile = PublisherProfile.get_default_profile()',
    '    print(f"\\n[Profile] Loaded: {profile.brand_name} ({profile.profile_id})")',
    '',
    '    # 2. Parse article into Visual Brief',
    '    article_path = Path(__file__).parent / "sample-article.md"',
    '    if not article_path.exists():',
    '        article_path = Path(__file__).resolve().parent.parent.parent / "examples" / "sample-article.md"',
    '',
    '    brief = VisualBrief.from_markdown(str(article_path))',
    '    brief.topic = "minimalist travel"',
    '    brief.detected_location = None',
    '    brief.article_language = "en"',
    '    brief.article_id = "demo-article-001"',
    '',
    '    print(f"\\n[1/4] Visual Brief")',
    '    print(f"  Title:    {brief.article_title}")',
    '    print(f"  Sections: {len(brief.sections)}")',
    '    print(f"  Slots:    {len(brief.image_slots)}")',
    '    for slot in brief.image_slots:',
    '        print(f"    - {slot[\'slot_id\']}: {slot[\'purpose\']} ({slot[\'preferred_type\']})")',
    '',
    '    # 3. Score all candidates for each slot',
    '    print(f"\\n[2/4] Fit Scores ({len(MOCK_CANDIDATES)} candidates x {len(brief.image_slots)} slots)")',
    '    all_scores = []',
    '    for slot in brief.image_slots:',
    '        slot_scores = []',
    '        for cand in MOCK_CANDIDATES:',
    '            score = score_candidate(cand, slot, brief)',
    '            slot_scores.append(score)',
    '        slot_scores.sort(key=lambda s: s.final_score, reverse=True)',
    '        all_scores.append((slot, slot_scores))',
    '',
    '        best = slot_scores[0]',
    '        print(f"  Slot \'{slot[\'slot_id\']}\':")',
    '        for s in slot_scores:',
    '            icon = "v" if s.decision == "selected" else ("x" if s.decision == "rejected" else "?")',
    '            print(f"    {icon} {s.candidate_id}: {s.final_score:.1f} ({s.decision}) -- {s.human_reason}")',
    '',
    '    # 4. Select best candidate per slot & build Provenance Packs',
    '    print(f"\\n[3/4] Provenance Packs")',
    '    packs = []',
    '    selected_map = {}  # slot_id -> candidate',
    '    used_ids = set()',
    '',
    '    for slot, slot_scores in all_scores:',
    '        for score in slot_scores:',
    '            if score.decision == "selected" and score.candidate_id not in used_ids:',
    '                cand = next(c for c in MOCK_CANDIDATES if c["id"] == score.candidate_id)',
    '                used_ids.add(score.candidate_id)',
    '                selected_map[slot["slot_id"]] = cand',
    '',
    '                content = f"{cand[\'id\']}:{cand[\'filename\']}"',
    '                chash = hashlib.sha256(content.encode()).hexdigest()[:16]',
    '                gen_name = f"pictovap_{cand[\'filename\'].rsplit(\'.\', 1)[0]}.webp"',
    '',
    '                pack = ProvenancePack(',
    '                    image_id=cand["id"],',
    '                    source_type=cand.get("source_type", "local"),',
    '                    provider=cand.get("provider", "local"),',
    '                    source_url=cand.get("source_url"),',
    '                    local_source_path=cand.get("local_path"),',
    '                    license_status=cand.get("license", "unknown"),',
    '                    attribution=cand.get("attribution"),',
    '                    original_filename=cand["filename"],',
    '                    generated_filename=gen_name,',
    '                    content_hash=chash,',
    '                    article_id=brief.article_id,',
    '                    slot_id=slot["slot_id"],',
    '                    placement_target=slot.get("purpose", ""),',
    '                    generated_alt_text=f"A {\', \'.join(cand.get(\'keywords\', [])[:3])} scene",',
    '                    generated_caption=f"Visual for: {slot.get(\'target_heading\', brief.article_title)}",',
    '                    processing_actions=["resize_1200", "webp_convert", "exif_strip"],',
    '                )',
    '                packs.append(pack)',
    '                print(f"  {pack.slot_id}: {pack.original_filename} -> {pack.generated_filename}")',
    '                print(f"    Provider: {pack.provider}, License: {pack.license_status}, Hash: {pack.content_hash}")',
    '                break',
    '',
    '    # 5. Build CMS Placement plan',
    '    print(f"\\n[4/4] CMS Placement Plan")',
    '    instructions = []',
    '    for pack in packs:',
    '        slot = next((s for s in brief.image_slots if s["slot_id"] == pack.slot_id), {})',
    '        instr = PlacementInstruction(',
    '            slot_id=pack.slot_id,',
    '            output_path=pack.generated_filename,',
    '            target_section=slot.get("target_heading", ""),',
    '            placement_strategy="featured" if pack.slot_id == "featured" else "after_heading",',
    '            image_role="featured" if pack.slot_id == "featured" else "content",',
    '            alt_text=pack.generated_alt_text,',
    '            caption=pack.generated_caption,',
    '        )',
    '        instructions.append(instr)',
    '        print(f"  [{instr.image_role}] {instr.output_path} -> {instr.placement_strategy}:{instr.target_section or \'top\'}")',
    '',
    '    placement = CMSPlacement(',
    '        article_id=brief.article_id,',
    '        adapter_target="mock_adapter",',
    '        target_platform="demo",',
    '        placements=instructions,',
    '    )',
    '',
    '    # 6. Assemble full output',
    '    output = {',
    '        "pipeline": "Pictovap Visual Finishing Demo",',
    '        "visual_brief": brief.to_dict(),',
    '        "fit_scores": {',
    '            slot["slot_id"]: [s.to_dict() for s in scores]',
    '            for slot, scores in all_scores',
    '        },',
    '        "provenance_packs": [p.to_dict() for p in packs],',
    '        "cms_placement": placement.to_dict(),',
    '        "profile": {',
    '            "id": profile.profile_id,',
    '            "brand": profile.brand_name,',
    '            "cms_type": profile.cms_type,',
    '            "language": profile.language,',
    '        },',
    '    }',
    '',
    '    # 7. Write output file',
    '    out_path = Path(__file__).parent / "sample-output.json"',
    '    if not out_path.parent.exists() or out_path.parent.name == "pictova":',
    '        out_path = Path(__file__).resolve().parent.parent.parent / "examples" / "sample-output.json"',
    '    out_path.write_text(json.dumps(output, indent=2, ensure_ascii=False), encoding="utf-8")',
    '',
    '    print(f"\\n{\'=\' * 60}")',
    '    print(f"  Output written to: {out_path}")',
    '    print(f"  Brief:      {len(brief.image_slots)} slots from {len(brief.sections)} sections")',
    '    print(f"  Evaluated:  {len(MOCK_CANDIDATES)} candidates")',
    '    print(f"  Selected:   {len(packs)} images")',
    '    print(f"  Rejected:   {sum(1 for _, ss in all_scores for s in ss if s.decision == \'rejected\')} candidates")',
    '    print(f"  Placements: {len(placement.placements)} instructions")',
    '    print(f"{\'=\' * 60}")',
    '    print("  Demo completed. No credentials were used.")',
    '    print()',
    '',
    '',
    'if __name__ == "__main__":',
    '    run_demo()',
]
rewrite_file('src/pictova/demo.py', src_pictova_demo_py_lines)

tests_unit_test_demo_py_lines: list[str] = [
    '"""',
    'Tests for the Pictovap local demo.',
    '',
    'Proves:',
    '- demo module is importable',
    '- run_demo() runs without any .env or credentials',
    '- examples/sample-output.json is produced after the run',
    '- all four primitives serialize correctly',
    '- docs/README.md links point to files that exist',
    '"""',
    '',
    'import json',
    'import os',
    'import re',
    'from pathlib import Path',
    '',
    'import pytest',
    '',
    '',
    'REPO_ROOT = Path(__file__).resolve().parent.parent.parent',
    'DOCS_README = REPO_ROOT / "docs" / "README.md"',
    'EXAMPLES_OUTPUT = REPO_ROOT / "examples" / "sample-output.json"',
    '',
    '',
    '# ---------------------------------------------------------------------------',
    '# 1. Demo module is importable',
    '# ---------------------------------------------------------------------------',
    '',
    'def test_demo_module_importable():',
    '    """The demo module must import without errors."""',
    '    from pictova import demo  # noqa: F401',
    '    assert hasattr(demo, "run_demo"), "run_demo function must exist in demo module"',
    '',
    '',
    '# ---------------------------------------------------------------------------',
    '# 2. Demo runs without .env or credentials',
    '# ---------------------------------------------------------------------------',
    '',
    'def test_demo_runs_without_env(tmp_path, monkeypatch):',
    '    """',
    '    run_demo() must complete without any environment credentials.',
    '    We strip any inherited credential env vars and verify the demo still runs.',
    '    """',
    '    credential_vars = [',
    '        "WORDPRESS_URL", "WORDPRESS_USERNAME", "WORDPRESS_APP_PASSWORD",',
    '        "UNSPLASH_ACCESS_KEY", "DEPOSITPHOTOS_API_KEY",',
    '        "GEMINI_API_KEY", "ANTHROPIC_API_KEY", "OPENAI_API_KEY",',
    '        "YO_VISUAL_MEMORY_DB", "LM_STUDIO_URL",',
    '    ]',
    '    for var in credential_vars:',
    '        monkeypatch.delenv(var, raising=False)',
    '',
    "    # Override output path so it writes to tmp_path and doesn't clobber examples/",
    '    monkeypatch.chdir(tmp_path)',
    '',
    '    from pictova.demo import run_demo',
    '    # Must not raise — if it does, the test fails with the actual exception',
    '    run_demo()',
    '',
    '',
    '# ---------------------------------------------------------------------------',
    '# 3. sample-output.json is produced',
    '# ---------------------------------------------------------------------------',
    '',
    'def test_sample_output_produced():',
    '    """',
    '    After running the demo, examples/sample-output.json must exist and be',
    '    valid JSON containing the four primitive keys.',
    '    """',
    '    from pictova.demo import run_demo',
    '    run_demo()',
    '',
    '    assert EXAMPLES_OUTPUT.exists(), (',
    '        f"Expected {EXAMPLES_OUTPUT} to exist after demo run"',
    '    )',
    '',
    '    data = json.loads(EXAMPLES_OUTPUT.read_text(encoding="utf-8"))',
    '    assert "visual_brief" in data, "Output must contain visual_brief"',
    '    assert "fit_scores" in data, "Output must contain fit_scores"',
    '    assert "provenance_packs" in data, "Output must contain provenance_packs"',
    '    assert "cms_placement" in data, "Output must contain cms_placement"',
    '',
    '',
    '# ---------------------------------------------------------------------------',
    '# 4. All four primitives serialize correctly',
    '# ---------------------------------------------------------------------------',
    '',
    'def test_visual_brief_serializes():',
    '    from pictova.core.primitives import VisualBrief',
    '    brief = VisualBrief(',
    '        article_title="Test Article",',
    '        topic="testing",',
    '        sections=[{"heading": "Intro", "level": "h2"}],',
    '        image_slots=[{"slot_id": "featured", "purpose": "featured_image", "preferred_type": "landscape"}],',
    '    )',
    '    data = brief.to_dict()',
    '    assert data["article_title"] == "Test Article"',
    '    assert data["topic"] == "testing"',
    '    assert len(data["sections"]) == 1',
    '    assert len(data["image_slots"]) == 1',
    '',
    '',
    'def test_fit_score_serializes():',
    '    from pictova.core.primitives import FitScore',
    '    score = FitScore(',
    '        candidate_id="img-test",',
    '        final_score=9.5,',
    '        decision="selected",',
    '        human_reason="Strong fit",',
    '    )',
    '    data = score.to_dict()',
    '    assert data["candidate_id"] == "img-test"',
    '    assert data["final_score"] == 9.5',
    '    assert data["decision"] == "selected"',
    '',
    '',
    'def test_provenance_pack_serializes():',
    '    from pictova.core.primitives import ProvenancePack',
    '    pack = ProvenancePack(',
    '        image_id="img-001",',
    '        provider="local",',
    '        original_filename="test.jpg",',
    '        generated_filename="pictovap_test.webp",',
    '        content_hash="abc123",',
    '        slot_id="featured",',
    '        placement_target="featured_image",',
    '        generated_alt_text="A test scene",',
    '        generated_caption="Test caption",',
    '    )',
    '    data = pack.to_dict()',
    '    assert data["image_id"] == "img-001"',
    '    assert data["provider"] == "local"',
    '    assert "timestamp" in data',
    '    assert data["timestamp"] is not None',
    '',
    '',
    'def test_cms_placement_serializes():',
    '    from pictova.core.primitives import CMSPlacement, PlacementInstruction',
    '    placement = CMSPlacement(',
    '        article_id="test-article",',
    '        adapter_target="mock",',
    '        target_platform="demo",',
    '        placements=[',
    '            PlacementInstruction(',
    '                slot_id="featured",',
    '                output_path="pictovap_test.webp",',
    '                target_section="",',
    '                placement_strategy="featured",',
    '                image_role="featured",',
    '                alt_text="A test scene",',
    '                caption="Test caption",',
    '            )',
    '        ],',
    '    )',
    '    data = placement.to_dict()',
    '    assert data["article_id"] == "test-article"',
    '    assert data["target_platform"] == "demo"',
    '    assert len(data["placements"]) == 1',
    '    assert data["placements"][0]["slot_id"] == "featured"',
    '',
    '',
    '# ---------------------------------------------------------------------------',
    '# 5. docs/README.md links point to existing files',
    '# ---------------------------------------------------------------------------',
    '',
    'def test_docs_readme_links_resolve():',
    '    """',
    '    Every relative markdown link in docs/README.md must point to a file',
    '    that exists on disk.',
    '    """',
    '    assert DOCS_README.exists(), f"{DOCS_README} must exist"',
    '',
    '    content = DOCS_README.read_text(encoding="utf-8")',
    '    docs_dir = DOCS_README.parent',
    '',
    '    # Match markdown links: [text](target) — only relative links (no http/https)',
    "    link_pattern = re.compile(r'\\[([^\\]]+)\\]\\(([^)]+)\\)')",
    '    broken = []',
    '',
    '    for match in link_pattern.finditer(content):',
    '        link_text, link_target = match.group(1), match.group(2)',
    '',
    '        # Skip external links and anchors',
    '        if link_target.startswith("http") or link_target.startswith("#"):',
    '            continue',
    '',
    '        # Strip fragment',
    '        path_part = link_target.split("#")[0]',
    '        if not path_part:',
    '            continue',
    '',
    '        resolved = (docs_dir / path_part).resolve()',
    '        if not resolved.exists():',
    '            broken.append(f"  [{link_text}]({link_target}) -> {resolved}")',
    '',
    '    assert not broken, (',
    '        f"docs/README.md contains {len(broken)} broken link(s):\\n" +',
    '        "\\n".join(broken)',
    '    )',
]
rewrite_file('tests/unit/test_demo.py', tests_unit_test_demo_py_lines)

tests_unit_test_file_formatting_py_lines: list[str] = [
    '"""',
    'Test guard: verify that public repository files have not been collapsed',
    'into single-line or malformed blobs by automated tooling.',
    '',
    'Each file must have at least its expected minimum number of physical lines.',
    '"""',
    '',
    'import pytest',
    'from pathlib import Path',
    '',
    '',
    'REPO_ROOT = Path(__file__).resolve().parent.parent.parent',
    '',
    'MINIMUM_LINES = {',
    '    "README.md": 40,',
    '    "Makefile": 20,',
    '    ".github/workflows/ci.yml": 40,',
    '    "docs/README.md": 20,',
    '    "docs/ARCHITECTURE.md": 40,',
    '    "examples/profiles/sample-publisher.yaml": 25,',
    '    "src/pictova/demo.py": 120,',
    '    "tests/unit/test_demo.py": 80,',
    '    "tests/unit/test_file_formatting.py": 25,',
    '    "pyproject.toml": 30,',
    '}',
    '',
    '',
    'def line_count(path):',
    '    """Return the number of physical lines in the file."""',
    '    p = Path(path)',
    '    if not p.exists():',
    '        return 0',
    '    return len(p.read_text(encoding="utf-8").splitlines())',
    '',
    '',
    '@pytest.mark.parametrize(',
    '    "rel_path,minimum",',
    '    list(MINIMUM_LINES.items()),',
    '    ids=list(MINIMUM_LINES.keys()),',
    ')',
    'def test_public_file_not_collapsed(rel_path, minimum):',
    '    """Each public file must have at least {minimum} physical lines."""',
    '    path = REPO_ROOT / rel_path',
    '    actual = line_count(path)',
    '    assert actual >= minimum, (',
    '        f"{rel_path} appears collapsed or malformed: "',
    '        f"{actual} lines, expected at least {minimum}"',
    '    )',
]
rewrite_file('tests/unit/test_file_formatting.py', tests_unit_test_file_formatting_py_lines)

pyproject_toml_lines: list[str] = [
    '[build-system]',
    'requires = ["setuptools>=68", "wheel"]',
    'build-backend = "setuptools.build_meta"',
    '',
    '[project]',
    'name = "pictovap"',
    'version = "0.2.0"',
    'description = "Open-source visual finishing engine for content publishers."',
    'readme = "README.md"',
    'requires-python = ">=3.9"',
    'license = {text = "MIT"}',
    'authors = [',
    '    {name = "Pictovap Contributors", email = "hello@yoldaolmak.com"}',
    ']',
    'keywords = [',
    '    "wordpress", "image automation", "llm", "vision", "seo", "cms", "mac photos", "unsplash"',
    ']',
    'classifiers = [',
    '    "Development Status :: 4 - Beta",',
    '    "Intended Audience :: Developers",',
    '    "License :: OSI Approved :: MIT License",',
    '    "Topic :: Multimedia :: Graphics",',
    '    "Topic :: Software Development :: Libraries :: Python Modules",',
    '    "Programming Language :: Python :: 3.9",',
    '    "Programming Language :: Python :: 3.10",',
    '    "Programming Language :: Python :: 3.11",',
    ']',
    'dependencies = [',
    '    "Pillow>=9.0.0",',
    '    "anthropic>=0.3.0",',
    '    "requests>=2.25.0",',
    '    "numpy>=1.20.0",',
    ']',
    '',
    '[project.optional-dependencies]',
    'test = [',
    '    "pytest>=7.4.0",',
    '    "pytest-cov>=4.1.0",',
    '    "pytest-asyncio>=0.21.0",',
    ']',
    '',
    '[project.urls]',
    'Homepage = "https://github.com/yoldaolmak/Pictovap"',
    'Documentation = "https://github.com/yoldaolmak/Pictovap/blob/main/docs/README.md"',
    'Repository = "https://github.com/yoldaolmak/Pictovap.git"',
    '',
    '[project.scripts]',
    'pictova = "pictova.app.cli:main"',
    'pictovap = "pictova.app.cli:main"',
    '',
    '[tool.setuptools.packages.find]',
    'where = ["src"]',
    'namespaces = false',
]
rewrite_file('pyproject.toml', pyproject_toml_lines)

examples_profiles_sample_publisher_yaml_lines: list[str] = [
    'profile_id: sample-publisher',
    'brand_name: Sample Publisher',
    'cms_type: generic',
    'language: en',
    '',
    'image_sources:',
    '  - local',
    '',
    'output_rules:',
    '  format: webp',
    '  max_width: 1200',
    '  max_height: 800',
    '  quality: 85',
    '',
    'filename_rules:',
    '  prefix: pictovap_',
    '  case: lowercase',
    '  separator: "-"',
    '',
    'alt_text_rules:',
    '  language: en',
    '  max_length: 125',
    '  avoid_word: image',
    '',
    'caption_rules:',
    '  language: en',
    '  include_attribution: true',
    '',
    'editorial_preferences:',
    '  tone: neutral',
    '  style: documentary',
    '',
    'forbidden_patterns:',
    '  - tourists holding maps',
    '  - stock photo handshake',
    '  - generic office backgrounds',
]
rewrite_file('examples/profiles/sample-publisher.yaml', examples_profiles_sample_publisher_yaml_lines)

docs_README_md_lines: list[str] = [
    '# Pictovap Documentation',
    '',
    'Welcome to the documentation for **Pictovap**, an open-source visual finishing engine',
    'for content publishers.',
    '',
    '## Getting Started',
    '',
    '- [Quickstart](quickstart.md) — Install and run the local demo in under five minutes.',
    '- [Architecture](ARCHITECTURE.md) — Understand how the pipeline works.',
    '',
    '## Core Concepts',
    '',
    '- [Visual Brief](concepts/visual-brief.md) — Structured visual requirements extracted from articles.',
    '- [Fit Score](concepts/fit-score.md) — Transparent candidate image evaluation.',
    '- [Provenance Pack](concepts/provenance-pack.md) — Audit trail for selected images.',
    '- [CMS Placement](concepts/cms-placement.md) — CMS-agnostic placement instructions.',
    '',
    '## Reference',
    '',
    '- [Publisher Profiles](reference/publisher-profiles.md) — Per-publisher configuration.',
    '- [CLI Reference](CLI_REFERENCE.md) — Command-line interface.',
    '- [Configuration](reference/configuration.md) — Environment variables and settings.',
    '',
    '## Adapters',
    '',
    '- [Adapter Overview](adapters/overview.md) — How to extend Pictovap.',
    '- [Image Sources](adapters/image-sources.md) — Adding new image providers.',
    '- [CMS Adapters](adapters/cms-adapters.md) — Adding new CMS targets.',
    '',
    '## Contributing',
    '',
    '- [Contributing Guide](../CONTRIBUTING.md)',
    '- [Writing Adapters](contributing/adapters.md)',
    '- [Good First Issues](contributing/good-first-issues.md)',
    '',
    '## Case Studies',
    '',
    '- [Yoldaolmak.com](case-studies/yoldaolmak.md) — Real-world dogfooding case study.',
]
rewrite_file('docs/README.md', docs_README_md_lines)

docs_ARCHITECTURE_md_lines: list[str] = [
    '# Pictovap Architecture',
    '',
    'Pictovap is an open-source visual finishing engine for content publishers.',
    'It is designed as a headless, modular pipeline that transforms raw text content',
    'into a fully visually-populated publishing package.',
    '',
    '## 1. Product Boundary',
    '',
    'Pictovap solves the gap between "the text is written" and "the page is visually',
    'complete and published in the CMS."',
    '',
    'It is **not**:',
    '- A stock photo search tool',
    '- A Digital Asset Management (DAM) system',
    '- A generic AI image generator',
    '',
    'It is the article-aware automation layer that understands editorial layout needs,',
    'selects matching images, tracks licensing provenance, generates metadata, and',
    'places the images into the CMS.',
    '',
    '## 2. Core Primitives',
    '',
    'The architecture revolves around four core data primitives',
    '(defined in `src/pictova/core/primitives.py`) that move sequentially',
    'through the pipeline:',
    '',
    '1. **[Visual Brief](concepts/visual-brief.md)**: Structured extraction of what',
    '   imagery the article needs, based on heading structure and content.',
    '2. **[Fit Score](concepts/fit-score.md)**: Transparent, deterministic evaluation',
    "   of candidate images against the brief's requirements (context, quality, license).",
    '3. **[Provenance Pack](concepts/provenance-pack.md)**: Persistent audit trail',
    '   recording the origin, license, processing actions, and generated metadata',
    '   for every selected image.',
    '4. **[CMS Placement](concepts/cms-placement.md)**: CMS-agnostic plan for where',
    '   images should be injected into the target platform.',
    '',
    '## 3. Data Flow',
    '',
    'The engine operates sequentially:',
    '',
    '```text',
    'Analysis (Visual Brief)',
    '  -> Selection (Fit Score)',
    '  -> Processing (Provenance Pack)',
    '  -> Placement (CMS Placement)',
    '```',
    '',
    'Each stage produces a serializable object that feeds the next. The core engine',
    'orchestrates this flow without any hardcoded dependencies on external systems.',
    '',
    '## 4. Adapter Model',
    '',
    'Pictovap connects to the outside world via two types of adapters:',
    '',
    '- **Image Source Adapters** (`src/pictova/providers/`): Supply candidate images.',
    '  Examples: Local directory, Unsplash, DepositPhotos.',
    '- **CMS Placement Adapters** (`src/pictova/publishers/`): Consume the CMS',
    '  Placement plan and execute native API calls.',
    '  Examples: WordPress, Ghost, Strapi.',
    '',
    'The core pipeline is adapter-agnostic.',
    '',
    '## 5. Credential-Free Demo Path',
    '',
    'The local demo (`make demo`) runs the entire pipeline end-to-end without',
    'requiring any external credentials, API keys, or CMS connections. It uses:',
    '',
    '- A local directory of mock image metadata as the source adapter.',
    '- Deterministic rules for scoring and metadata generation.',
    '- A mock CMS adapter that outputs the placement plan to a local JSON file.',
    '',
    '## 6. WordPress as One CMS Adapter',
    '',
    'While WordPress is currently the most production-hardened target, it is merely',
    'one CMS adapter implementation. Pictovap does not assume WordPress as the',
    'conceptual center. Any CMS with an API can be supported by writing a new adapter',
    'that consumes the `CMSPlacement` primitive.',
    '',
    '## 7. Yoldaolmak.com as Dogfooding Case Study',
    '',
    'Pictovap was extracted from the production infrastructure of a travel publisher,',
    "yoldaolmak.com. The site's profile (`src/pictova/profiles/yoldaolmak.py`) and",
    'specific constraints represent a dogfooding case study and one possible',
    'configuration, not the default path or product center.',
    '',
    '## 8. Metadata Generation as Optional Adapter Behavior',
    '',
    'While Pictovap produces standard metadata (Alt Text, SEO Title, Caption), the',
    'exact mechanism is source-agnostic. It may be generated via an AI metadata',
    'adapter (e.g., Gemini, Claude, LM Studio) or fall back to rule-based templates.',
    'No specific AI model or "Vision Chain" is a required architectural component.',
    '',
    '## 9. Legacy Package/CLI Compatibility',
    '',
    '- **Product name:** Pictovap.',
    '- Python package, directories (e.g., `src/pictova/`), and legacy CLI commands',
    '  may remain `pictova` for backward compatibility.',
    '',
    '## 10. Current Limitations',
    '',
    '- Core logic was recently extracted from production; some internal dict passing',
    '  is still being migrated to strict primitives.',
    '- Only the WordPress CMS adapter is production-hardened; others are reference stubs.',
    '- Publisher profiles exist as Python dataclasses but are not yet fully loadable',
    '  from YAML in all pipeline paths.',
    '',
    '## Engine Layout',
    '',
    '```',
    'src/',
    '  pictova/',
    '    app/          # CLI and REST API entrypoints',
    '    core/         # Primitives and shared data structures',
    '    engine/       # The pipeline (Analysis, Selection, Processing)',
    '    filters/      # Image processing algorithms',
    '    profiles/     # Publisher configurations',
    '    providers/    # Image source adapters',
    '    publishers/   # CMS integration adapters',
    '```',
]
rewrite_file('docs/ARCHITECTURE.md', docs_ARCHITECTURE_md_lines)
